//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoard
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public System.DateTime DateLogged { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ImageUrl { get; set; }
        public string IPAddress { get; set; }
        public string Latitute { get; set; }
        public string Longitude { get; set; }
    
        public virtual User User { get; set; }
    }
}
