//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DepartmentOfPublicWorksEntities : DbContext
    {
        public DepartmentOfPublicWorksEntities()
            : base("name=DepartmentOfPublicWorksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DashBoard> DashBoards { get; set; }
        public virtual DbSet<DataLookUp> DataLookUps { get; set; }
        public virtual DbSet<LookUpName> LookUpNames { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
